name: Build Application

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          echo "Running tests..."

      - name: Build Docker Image
        run: |
          docker build \
            -t myapp:${{ github.sha }} .

      - name: Security Scan
        run: |
          echo "Run Trivy or another scanner"

      - name: Push Image
        run: |
          echo "Push image to container registry"
